### NUMPY - DATACAMP - 1
<hr>
<br>

#### Numpy Array

- Numpy arrays allow a user to make calculations on elements **in-order**
- While you couldn't do something like the following with Python _Lists_, you **can** do with numpy:
```
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])     # In meters
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])     # In kilos
bmi = weight / height ** 2
# lists = *** ERROR ***
# nparrays = array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])
```
- Numpy can work with arrays as though they were single values. The same cannot be done with the default _lists_
- Numpy arrays, like classical arrays, must have a homogenous datatype . You cannot mix datatypes like with _lists_
- You can also do handy math on numpy arrays like the following:
```
bmi > 23
# array([False, False, False,  True, False])
```

In [3]:
import numpy as np 

height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])     # In meters
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])     # In kilos
bmi = weight / height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [4]:
bmi[2]

21.750282138093777

In [5]:
bmi > 23

array([False, False, False,  True, False])