In [1]:
import numpy as np

*These first examples are _casting_ regular python lists to numpy arrays*

In [2]:
reg_list = [1,2,3,'h']
norm_list = [55,83,203]

arr = np.array(reg_list)
reg_arr = np.array(norm_list)
arr

array(['1', '2', '3', 'h'], dtype='<U21')

In [3]:
reg_arr

array([ 55,  83, 203])

*You can manually create matrices, etc*

In [4]:
my_matrice = [[1,2,3],[4,5,6],[7,8,9]]
cast_matrix = np.array(my_matrice)

In [5]:
cast_matrix.ndim


2

In [6]:
cast_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*To create arrays _'intrinsically'_ within numpy.. use _arrange()_*
- Takes arguments of _start_, _stop_ and _step_ for indexing.
- Very similar to python's _range()_

In [7]:
npy_arr1 = np.arange(0,11,2) 
npy_arr1

array([ 0,  2,  4,  6,  8, 10])

In [11]:
two_d_from_list = np.array([[1,2,3], [4,5,6]])

two_d_from_list

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:

## Understanding shapes of arrays 

two_d_array = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))

holder = [reg_arr, two_d_from_list, two_d_array]

# two_d_array

for ele in holder:
    print(ele)

for shp in holder:
    print('shape: ', shp.shape)

[ 55  83 203]
[[1 2 3]
 [4 5 6]]
[[0 2 4 6]
 [1 3 5 7]]
shape:  (3,)
shape:  (2, 3)
shape:  (2, 4)


In [20]:
two_d_from_list.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])